//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Estructura de Datos 1er Entrega.rc
//
#define ID_InicioSesion                 101
#define ID_MENU                         103
#define IDR_MENU1                       104
#define ID_RegisPersona                 108
#define ID_RegistrarVacuna              110
#define ID_ListaVacuna                  112
#define ID_ListaPersona                 114
#define ID_RegistrarCarnet              116
#define ID_ListaCarnet                  118
#define ID_InicioSesClave               1001
#define ID_InicioSesContra              1002
#define ID_RegistrarClave               1003
#define ID_RegistrarContra              1004
#define ID_RegistrarNombre              1005
#define ID_bIniciar                     1006
#define ID_RegistrarApllPat             1007
#define ID_RegistrarContra2             1008
#define ID_RegistrarApllMat             1008
#define ID_bRegistrarse                 1009
#define ID_RegisPersonaApllMat          1010
#define ID_RegisPersonaApllPat          1011
#define ID_RegisPersonaNombres          1012
#define ID_RegisPersonaCurp             1013
#define ID_RegisPersonaFechaNacimiento  1016
#define ID_RegisPersonaDireccion        1017
#define ID_RegisPersonaEstCivil         1019
#define ID_RegisPersonaTelefono         1020
#define ID_RegisPersonaSexo             1021
#define ID_RegisPersonaRFC              1022
#define ID_RegisPersonaGpoOcpcnl        1023
#define ID_RegisPersonaPrflRiesgo       1024
#define ID_RegisPersonaFoto             1025
#define ID_bRegisPersonaFoto            1026
#define ID_bRegisPersonaDocumento       1027
#define ID_RegisPersonaDocumento        1028
#define ID_bRegistrarPersona            1029
#define ID_bRegisPersonaSalir           1030
#define ID_RegisVacunaTipo              1031
#define ID_RegisVacunaMarca             1032
#define ID_RegisVacunaNo                1033
#define ID_RegisVacunaClave             1034
#define ID_RegisVacunaDesc              1035
#define ID_RegisVacunaPrecio            1036
#define ID_bRegistrarVacuna             1037
#define ID_bRegisVacunaSalir            1038
#define ID_RegisPersonaCalle            1039
#define ID_RegisPersonaColonia          1040
#define ID_RegisPersonaCiudad           1041
#define ID_RegisPersonaestado           1042
#define ID_ListaVacunaTipo              1043
#define ID_ListaVacunaMarca             1044
#define ID_ListaVacunaNo                1045
#define ID_ListaVacunaClave             1046
#define ID_ListaVacunaDesc              1047
#define ID_ListaVacunaPrecio            1048
#define IDC_LIST2                       1052
#define ID_ListaListVacuna              1052
#define ID_bListaElimVacuna             1053
#define ID_bListaModifVacuna            1054
#define ID_bSalirListaVacuna            1055
#define ID_ListaListPersona             1056
#define ID_ListaPersonaApllPat          1058
#define ID_ListaPersonaApllMat          1059
#define ID_ListaPersonaNombres          1060
#define ID_ListaPersonaCurp             1061
#define ID_ListaPersonaRFC              1062
#define ID_ListaPersonaFechaNacimiento  1063
#define ID_ListaPersonaColonia          1064
#define ID_ListaPersonaCiudad           1065
#define ID_ListaPersonaestado           1066
#define ID_ListaPersonaEstCivil         1067
#define ID_ListaPersonaTelefono         1068
#define ID_ListaPersonaSexo             1069
#define ID_ListaPersonaGpoOcpcnl        1070
#define ID_ListaPersonaPrflRiesgo       1071
#define ID_bListaPersonaFoto            1072
#define ID_bListaPersonaDocumento       1073
#define ID_ListaPersonaDocumento        1074
#define ID_ListaPersonaFoto             1075
#define ID_bListaPersonaModif           1076
#define ID_bListaPersonaElim            1077
#define ID_bListaPersonaSalir           1078
#define ID_ListaPersonaCalle            1079
#define ID_RegisCarnetCurp              1080
#define ID_RegisCarnetDosis             1081
#define ID_RegisCarnetFecha             1083
#define ID_RegisCarnetLote              1084
#define ID_RegisCarnetCentro            1085
#define ID_bRegisCarnetRegistrar        1086
#define ID_bRegisCarnetSalir            1087
#define ID_RegisCarnetClave             1088
#define ID_ListaCarnetCurp              1089
#define ID_ListaCarnetVacuna            1090
#define ID_ListaCarnetDosis             1092
#define ID_ListaCarnetFecha             1093
#define ID_ListaCarnetLote              1094
#define ID_ListaCarnetCentro            1095
#define ID_bListaCarnetBusBin           1096
#define ID_bListaCarnetBusSec           1097
#define ID_ListaCarnetBuscar            1098
#define ID_bListaCarnetSalir            1099
#define ID_ListaCarnetFoto              1101
#define ID_bListaCarnetBuscar           1102
#define ID_ListaCarnetElim              1103
#define ID_ListaCarnetModif             1104
#define ID_PERSONAS_REGISTRAR           40001
#define ID_VACUNAS_REGISTRAR            40002
#define ID_MenuPersonas                 40003
#define ID_Menu                         40004
#define ID_MenuVacunas                  40005
#define ID_USUARIO                      40006
#define ID_CARNET                       40007
#define ID_Salir                        40008
#define ID_VACUNAS                      40009
#define ID_PERSONAS                     40010
#define ID_VACUNAS_LISTA                40011
#define ID_PERSONAS_LISTA               40012
#define ID_CARNET_REGISTRAR             40013
#define ID_CARNET_LISTA                 40014

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        120
#define _APS_NEXT_COMMAND_VALUE         40015
#define _APS_NEXT_CONTROL_VALUE         1105
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
